### ISSUE TITLE
No token refresh call

### ISSUE THREAD

**Issue by anjaseidel** [zidatalab/ambulante_notfaelle#17]
My token is expired but I do not get a new one ...
/get_data returns 401 (detail: "Token expired") but no refresh token call takes place.

**Comment by lekroll** [comment]
Still a problem?

**Comment by anjaseidel** [comment]
Yes, it is a cross-origin problem: 

POST | https://dashboardapi.ziapp.de/get_data/


Status
401
Unauthorized
VersionHTTP/1.1
Transferred253 B (26 B size)
Referrer Policystrict-origin-when-cross-origin

Access-Control-Allow-Origin
	*
Access-Control-Expose-Headers
	*
Content-Length
	26
Content-Type
	application/json
Date
	Thu, 03 Feb 2022 14:54:02 GMT
Server
	uvicorn
WWW-Authenticate
	Bearer

Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Authorization
	Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZWlkZWxAemkuZGUiLCJhZG1pbiI6ZmFsc2UsInN1cGVyYWRtaW4iOnRydWUsImNsaWVudF9pZCI6InNtZWRfcmVwb3J0aW5nIiwiZXhwIjoxNjQzODk5OTQ3LCJmcmVzaCI6ZmFsc2V9.G-rxCnxsw5bg8d8sklQhMCfbzl1mEMbSDF7WvvyaBRQ
Connection
	keep-alive
Content-Length
	186
Content-Type
	application/json
Host
	dashboardapi.ziapp.de
Origin
	https://smed.ziapp.de
Referer
	https://smed.ziapp.de/
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-site
User-Agent
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
