### ISSUE TITLE
In plots: change format of numbers to comma-separated and 1 digit after comma

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#27]
Wenn man bei den Abbildungen mit der Maus drübergeht, sieht man die Daten der einzelnen Punkte. Hier werden die Zahlen bisher mit einem Punkt als Dezimaltrennzeichen und mit vier Stellen danach dargestellt. Bitte ändern zu Komma und eine Stelle nach dem Komma.

**Comment by Inoakabu** [comment]
That would be fixed.
