### ISSUE TITLE
Change the title of the dashboard

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#30]
as discussed with the scientific board of SmED and agreed to by Thomas Czihal:
lt. Protokoll: "Frau Dr. Slagmann [....] zeigt auf, dass die für das Dashboard gewählte Überschrift „Ambulante Akut- und Notfälle in Deutschland“ irreführend ist. Herr Czihal stimmt dem zu und kündigt eine Anpassung der Formulierung an."

--> evt. solange keine anderen Daten enthalten sind Änderung zu "Akut- und Notfälle bei der 116117"

**Comment by Inoakabu** [comment]
done
