### ISSUE TITLE
Single day analysis period is broken/inactivate "Erweiterte Analysen"

### ISSUE THREAD

**Issue by anjaseidel** [zidatalab/ambulante_notfaelle#33]
No data (or previous selected data) is shown if only one day is selected as analysis period at the "Tool für erweiterte Analysen".

**Comment by bzoch-lesniak** [comment]
Generell sind die Analysen in diesem Bereich problematisch/fehlerhaft. Rein die monatliche Anzahl der Assessments am Telefon pro KV stimmt für manche KVen und Monate nicht. Auf der Startseite stimmen die Zahlen. Bsp. KV Bayers September 2022: lt. Startseite 34.044 (stimmt auch überein mit HCSQ-Reporting), lt. erweiterte Analysen 33.337.
Mein Vorschlag: Wir nehmen die erweiterten Analysen insgesamt runter (Anzeige: "In Überarbeitung" oder so) und arbeiten da nochmal dran.

**Comment by anjaseidel** [comment]
according to Lars there are two different data sources: Databricks and MongoDB
TODO: check data in MongoDB which is used at the "Erweiterte Analysen"-section

**Comment by anjaseidel** [comment]
The data in the DB is fine. Problems are on the API-side (see pull request above) and on the Frontendside(see #37)

**Comment by anjaseidel** [comment]
The API is fixed and live.

**Comment by Inoakabu** [comment]
Is there anything been done here before? 

Because if I select a single Day to analyse from - it is working fine for me or am I just blind?

**Comment by bzoch-lesniak** [comment]
Ich weiß nicht wo jetzt noch genau der Fehler liegt, aber wenn wir beim o.g. Beispiel mit Bayern Sep 2022 bleiben, stimmt die Anzahl in den Erweiterten Analysen weiterhin nicht. Dort sind es jetzt 34.025, richtig wären 34.044.

**Comment by Inoakabu** [comment]
Da muss ich passen, die Daten kenne ich nicht und weiß deshalb nicht woran dass jetzt liegen könnte @anjaseidel kannst du dazu noch was sagen?

**Comment by anjaseidel** [comment]
Yes, the cause of the problem is https://github.com/zidatalab/ambulante_notfaelle/issues/37
If one selects the range 1.9.2022-30.9.2002 in the calendar, the wrong dates (31.8.2022-29.9.2022) are sent to the API (and the correct assessments for this time period are returned: 34025). If the correct start and stop dates are sent to the API, 34044 is returned.
![Screenshot from 2023-02-28 16-02-18](https://user-images.githubusercontent.com/63776292/221894620-f00d9b6a-b370-4152-bfa9-a86e693028d5.png)
![Screenshot from 2023-02-28 16-03-38](https://user-images.githubusercontent.com/63776292/221894658-e3d28090-d2bf-4558-8411-0a9acc6530b7.png)
![Screenshot from 2023-02-28 16-03-50](https://user-images.githubusercontent.com/63776292/221894682-841ed016-a8e8-46d4-8d7d-85f3996f386f.png)

**Comment by Inoakabu** [comment]
This should be fixed now. The Problem is, the error or misbehaviour wasn't really clear from the get go. So my testing sample size isn't that big and it needs to be further observed if this behaviour comes back at some point

Dates in JS are a tricky thing and converting dates into strings or other types isn't that small of a deal - vanilla JS speaking

**Comment by bzoch-lesniak** [comment]
Ich habe refreshed und Cookies gelöscht, bei mir werden dennoch für Sep 2022 für KVB 34.025 Assessments angezeigt.

**Comment by Inoakabu** [comment]
Das liegt daran weil die Änderungen noch nicht live sind - entschuldige die späte Antwort, eben erst gesehen dass du nachgefragt hast.

Aber ich denke bis Ende dieser Anfang nächster Woche sollten alle Änderungen dann live gehen. In absprache mit @lekroll
