### ISSUE TITLE
Calculation of SmED Assessments per 100.000 wrong?!!

### ISSUE THREAD

**Issue by anjaseidel** [zidatalab/ambulante_notfaelle#35]
Example: September 2022, Bayern
Return values of API:
Assessments = 34044
BEVSTAND = 13140183
Assessments per 100.000 inhabitants = (Assessments/BEVSTAND)*100000 = (34044/13140183)*100000 = 259,08

Value displayed in the plot: 303,1424

@lekroll : It looks like you are accidentally calculating with the KM6 instead of the BEVSTAND
KM6Versicherte = 11230364
(34044/11230364)*100000 = 303,1424
see https://github.com/zidatalab/ambulante_notfaelle/blob/cd55e0e355d15f04873ddadbff3cacd176c2c476/Dashboard/src/app/services/smed-aggregation.service.ts#L31

**Comment by bzoch-lesniak** [comment]
- Falls Berechnung mit KM6-Statistik bestehen bleiben soll, Änderung der Beschriftung in "pro 100.000 KV-Versicherte".
- Da wir sonst immer pro Einwohner angeben und auch privat Versicherte theoretisch anrufen dürfen (es wird nie gefragt, ob man gesetzlich oder privat versichert ist) fänd ich eine Änderung des Nenners zu Einwohner besser.

**Comment by Inoakabu** [comment]
After talking to @anjaseidel so I understand what is going here. We just need a decision:
1. do we change the text according to the data
2. we change the data according to the text

Please decide @lekroll @bzoch-lesniak - and let me know :)

**Comment by bzoch-lesniak** [comment]
Please change the data according to the text (pro 100 Tsd. **Einwohner**).
Danke! :)

**Comment by anjaseidel** [comment]
by merging the pull request? :-)
