### ISSUE TITLE
Fix analysis period at "Tool für erweiterte Analysen"

### ISSUE THREAD

**Issue by anjaseidel** [zidatalab/ambulante_notfaelle#37]
- Sometimes the wrong start and stop date are sent to the API e.g. if one selects the time period 01.09.2022 to 30.09.2022 then "startdate"=2022-08-31 and "stopdate"=2022-09.29 are sent (maybe due to the timezoneoffset?)
- it's not possible to select a single day time period (in this case only the startdate but not the stopdate is updated)

**Comment by Inoakabu** [comment]
Isn't that the same issue like 'Single day analysis period is broken/inactivate "Erweiterte Analysen" bug' ?

**Comment by anjaseidel** [comment]
Yeah, it's a bit overlapping :-) https://github.com/zidatalab/ambulante_notfaelle/issues/33 was my original issue for the Frontend but then Beate added some problems which were not only caused by Frontend bugs but also by API bugs (which I fixed in the meantime). Since everything got mixed up, I justed created this issue (again) with only Frontend errors.

**Comment by Inoakabu** [comment]
So this could be closed then?

**Comment by Inoakabu** [comment]
This should now be fixed on branch from other issue :)
