### ISSUE TITLE
Add plot like "SmED Assessments" but with absolute numbers

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#39]

**Comment by lekroll** [comment]
Please no new card but switch within card

**Comment by Inoakabu** [comment]
What exactly means "absolut numbers" in this context?

And it is a good idea to switch it and not add a new plot, I will go with that

**Comment by Inoakabu** [comment]
Aaah okay - ich verstehe :)
