### ISSUE TITLE
Zugriffsmöglichkeit für andere SmED-Nutzer einrichten

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#43]
Wie mit Lea und Frank besprochen, benötigen wir für andere SmED-Nutzer (also nicht KVen) für deren internes Qualitätsmanagement ein Dashboard bzw. eine Einbindung in dieses Dashboard mit anderen Zugriffsmöglichkeiten als für die KVen.
Die anderen Nutzer sollen nur ihre Daten sehen können. Es handelt sich größtenteils sich um dieselben Analysen/Plots.

- alle Kästchen oben
- Zeitreihe für Anzahl der Assessments (NICHT pro 100 Tsd. Einwohner),
- Häufigste Beschwerden
- Aufkommen nach Tag und Uhrzeit
- SmED-Empfehlung zu Dringlichkeit
- Zeitreihe Dauer
- Zeitreihe Anzahl Beschwerden
- Zeitreihe Anzahl Fragen
- Qualitätsparameter wie in Issue #42 

zusätzlich Geschlechts- und Alterszusammensetzung

**Comment by Inoakabu** [comment]
Ich gehe davon aus, dass das jetzt aber nicht mit den Bugfix Milestone übernommen wird - sondern dann im anschluss daran?

**Comment by bzoch-lesniak** [comment]
Zeitplan kläre ich noch, erstmal nicht anfassen.

**Comment by bzoch-lesniak** [comment]
@Inoakabu @lekroll @anjaseidel 
Neue Info: Es geht jetzt doch schon ab dem 01.07.2023 mit neuen Nutzern los. Ich kläre mal, wie diese neuen Nutzer in den Daten auftauchen werden und setze dann ein Meeting mit euch auf, um die notwendigen Schritte zu besprechen. 
An sich bleibt es erstmal bei denselben Analysen/Abbildungen wie jetzt auch, es müsste dann "nur" so funktionieren, dass bestimmte Nutzer nur ihre eigenen Daten sehen können.

**Comment by anjaseidel** [comment]
Nach Rücksprache mit @lekroll bitte zur Nutzerrechte-Implementierung @KodjoV  ansprechen, der über das nötige Wissen zu den entsprechenden API-Funktionen und Collectionen wie levelrights verfügt
