### ISSUE TITLE
Punkt als Tausendertrennzeichen und Komma als Dezimaltrennzeichen verwenden

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#44]
Bei den Zahlen in den oberen Kästchen (Assessments, Dauer in Sekunden, Anzahl Beschwerden, Anzahl Fragen) sind Punkt und Komma in englischer Schreibweise genutzt. Kannst du das bitte zu deutsch ändern? Also Punkt als Tausendertrennzeichen und Komma als Dezimaltrennzeichen.

**Comment by Inoakabu** [comment]
This is fixed
