### ISSUE TITLE
add Nordrhein and Westfalen-Lippe to Dashboard

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#46]
Bis 08.03.2023 hatten die KVen Nordrhein und Westfalen-Lippe ein gemeinsames Callcenter für die 116117, die Auswertung und Darstellung im Dashboard erfolgte insgesamt für "Nordrhein-Westfalen". Ab dem 14.03.2023 (bzw. davor, Nachlieferung erhalten wir demnächst) hat jede KV ihr eigenes Callcenter und eigene Lizenzen. Auswertungen sollten ab dem Zeitpunkt auch separat erfolgen.

Die Differenzierung nach KV Nordrhein und KV WL im SmED-Dashboard erfolgt lt. Anja doch nicht automatisch. Vermutlich müssen hier https://github.com/zidatalab/ambulante_notfaelle/blob/c8dca3b47b61257e9501f8e3816bd3d24daff534/Dashboard/src/app/pages/private/private.component.ts#L32 und hier https://github.com/zidatalab/ambulante_notfaelle/blob/c8dca3b47b61257e9501f8e3816bd3d24daff534/Dashboard/src/app/pages/start/start.component.ts#L36 zusätzlich zu "Nordrhein-Westfalen" "Nordrhein" und "Westfalen-Lippe" aufgelistet werden. Könntest du bei Gelegenheit mal lokal testen, ob du ab dem 14.03.2023 dann Assessment für Nordrhein und Westfalen-Lippe zurückkriegst?

**Comment by Inoakabu** [comment]
Also wenn diese Anpassungen auch im Backend sind, kann ich damit anfangen, ich werd aber auch schon mal anfangen die Abfrage zu implementieren.

**Comment by bzoch-lesniak** [comment]
Die Anpassungen sollten im Backend erfogt sein, oder @anjaseidel?

**Comment by anjaseidel** [comment]
In der Datenbank sollte es aufgesplittet sein. Ich hoffe, dass keine Anpassungen in der API erforderlich sind, aber das sehen wir dann, wenn @Inoakabu im Frontend nichts zurückbekommt :-D

**Comment by Inoakabu** [comment]
Update auch hier noch mal:

ist eingepflegt, Daten müssen noch geprüft werden
