### ISSUE TITLE
Bei externen Nutzern Abbildungen Abgleich Empfehlung vs. Entscheidung Dringlichkeit bzw. Behandlungsort entfernen

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#53]
Bei externen Nutzern Abbildungen Abgleich Empfehlung vs. Entscheidung Dringlichkeit bzw. Behandlungsort entfernen

**Comment by Inoakabu** [comment]
respiratorische Abbildung wieder hinzufügen und nur für nicht externe Anzeigen
