### ISSUE TITLE
Edit wording/text

### ISSUE THREAD

**Issue by bzoch-lesniak** [zidatalab/ambulante_notfaelle#55]
Bitte textliche Anpassungen wie in dem Dokument geschildert vornehmen (s. Spalte "Generelle Anpassungen"):
https://zentralinstitut.sharepoint.com/:p:/s/ZentraleProjektablage/EUQhoS7nEy1Ks9XaOr_DrokBZVGAucRA_pZ6X_Yumlyqrw?e=bk9lRp

@Inoakabu : Wenn du mit zeigst, wo ich das machen kann, kann ich das selbst machen.

**Comment by Inoakabu** [comment]
Everything done - besides changing Notations from "K" to "Tsd"

**Comment by bzoch-lesniak** [comment]
Super, danke! Dann mache ich für den Aspekt mit "K" to "Tsd" ein extra Issue auf und das hier zu.
